### ISSUE TITLE
Failing to register device as NTB 5.14.0

### ISSUE THREAD

**Issue by Prashankalikotayt** [Microsemi/switchtec-kernel#109]
I have installed the latest switchtec-kernel in debian 9.13.
Hardware being used is : PCI4-AD-x16HE-MG4 MS X16 EXT Host Adapter Card (this has Microchip PM40036 pcie switch).

Not able to figure out the issue.

dmesg output :

"13.947251] iTCO_wdt iTCO_wdt.1.auto: unable to reset NO_REBOOT flag, device disabled by hardware/BIOS
[   13.978934] switchtec switchtec0: Error setting up reserved lut window: 00030002 / 00000000
[   13.978990] switchtec switchtec0: failed to register ntb device: -5

"
PFA complete dmesg output
[dmesg.txt](https://github.com/Microsemi/switchtec-kernel/files/7684493/dmesg.txt)

**Comment by lsgunth** [comment]
Chances are the problem is with the configuration of the switch. It use to be that the example NTB configuration provided by Microsemi was close (save the note on the README). 

However, this error is indicating "LUT Window Exceeds BAR Size" which suggests there is not enough space configured for the LUTs in BAR1 in the configuration.

**Comment by Prashankalikotayt** [comment]
I have tried what you have suggested still getting the same error. However I dint understand what do you mean by "It use to be that the example NTB configuration provided by Microsemi was close (save the note on the README)."

**Comment by lsgunth** [comment]
I meant that Microsemi used to provide an example NTB configuration that didn't quite work with the switchtec_ntb driver, but the README has a not on what needs to be configured. 

What did you try exactly? How big are the BARs configured to be? What are the direct and LUT window configurations?

**Comment by Prashankalikotayt** [comment]
This is the NTB configuration file PFA provided by microchip. I have tried making some changes but that did not work. Since I am a novice I am not sure about the changes I have made.
[cfgFile_40036_for_git.csv](https://github.com/Microsemi/switchtec-kernel/files/7708840/cfgFile_40036_for_git.csv)
![Screenshot 2021-12-14 102916](https://user-images.githubusercontent.com/37098541/145936559-44dcc9d1-4bb6-4a60-a434-9823e6a6caba.png)
![Screenshot 2021-12-14 102943](https://user-images.githubusercontent.com/37098541/145936562-2885e1a0-58be-437d-a2a3-4f548f0009de.png)
![Screenshot 2021-12-14 103104](https://user-images.githubusercontent.com/37098541/145936563-11322359-d201-4c4d-90c5-7d536f4a6044.png)
![Screenshot 2021-12-14 103159](https://user-images.githubusercontent.com/37098541/145936564-e3c904e8-49df-463e-9a39-2cad29845eeb.png)

**Comment by Ilya-Novikov** [comment]
Probably, you should to check Management settings -> Partitions -> GAS access vector.
Set GAS access vector to allow access from both partitions to each partition, MRPC and Global Event sections.

**Comment by lsgunth** [comment]
It also looks like Bar2 and Bar4 need to be enabled in NT Endpoint Settings

**Comment by Prashankalikotayt** [comment]
Thanks @Ilya-Novikov I have done that in the configuration however it doesnt work. Thanks lsgunth I tried that still no luck. Looks like due to time zones the communication is getting delayed. Lets me put it together :
What I want to achieve : 

- Device sharing using the PM40036 PCIe switch using NTB.

Queries : 

- What is the required configuration for registering the device as NTB?
- What is configuration to be tried out for device sharing?

Thanks

**Comment by lsgunth** [comment]
Does it fail in the same way? Do the bars show up in the management endpoint in lspci?

Device sharing is a complicated topic that's not supported by the upstream driver. You will have to do a fair bit of work to get it working. I suggest you contact your Microchip rep about this.

**Comment by Prashankalikotayt** [comment]
It fails in the exact same way. The BARS do show up in the management endpoint.

**Comment by lsgunth** [comment]
If the BARS are not showing up there's still a problem with the confg or the new config is not getting enabled correctly.

**Comment by jborz27** [comment]
I noticed that neither translation mode (direct window or LUT) are enabled in the config for the NT BARs.

**Comment by Prashankalikotayt** [comment]
PFA for the lspci output of the system. @jborz27 Actually I have tried enabling either of them as well but still no luck or maybe I am not configuring the Direct Window or LUT correctly, any pointers on how to exactly configure them(Direct Window or LUT)
[lspci.txt](https://github.com/Microsemi/switchtec-kernel/files/7743313/lspci.txt)
?

**Comment by lsgunth** [comment]
> I noticed that neither translation mode (direct window or LUT) are enabled in the config for the NT BARs.

They should not be enabled in the configuration. The driver creates these.


The problem is there is no BAR 1.

**Comment by Prashankalikotayt** [comment]
> 

For BAR 1 to be visible BAR 0 should be set as 32-bit addressing, is that so? However I have tried doing that making BAR 1 visible after putting BAR 0 as 32 bit addressing, still I see the same error.

**Comment by lsgunth** [comment]
No, sorry I meant the problem is BAR2.

**Comment by Prashankalikotayt** [comment]
Can you tell what else could be tried.

**Comment by Prashankalikotayt** [comment]
We see BAR2 as on the last lspci output which I had shared

**Comment by lsgunth** [comment]
Oh, sorry I misread some of that. What's the top of the NT endpoint settings page look like? "Maxmum Number of NT Lut Entries" specifically?

**Comment by Prashankalikotayt** [comment]
Finally, the device got registered as you pointed out "Maximum Number of NT Lut Entries" it was set to 0 and I dint look into that. Thanks a lot.

**Comment by lsgunth** [comment]
Great! Good to hear.
