### ISSUE TITLE
Building in Kernel 4.15.0-22-generic requires explicit ccflags-y

### ISSUE THREAD

**Issue by yungwesl** [Microsemi/switchtec-kernel#14]
Just a note that when building in Ubuntu 18.04 (server) kernel 4.15.0-22-generic the make will fail because there needs to be an explicit path to stdarg.h

I've added 
-l/usr/lib/gcc/x86_64-linux-gnu/7.3.0/include

to the Kbuild ccflags-y for mine to build.  Even if you remove and re-add gcc this problem persists.

**Comment by lsgunth** [comment]
That's odd. stdarg.h is a standard header and if you need a command line argument for it there is something really wrong with your installation.

Moreover, switchtec-kernel doesn't use that header anywhere...

**Comment by yungwesl** [comment]
Thanks Logan

This was a stock install of Ubuntu Server 18.04 LTS.  Hopefully it shakes itself out in future releases.
