### ISSUE TITLE
How does switchtec-kernel work across two switchtec chips?

### ISSUE THREAD

**Issue by honda724** [Microsemi/switchtec-kernel#2]
Hi,

I want to make shared memory (or CMI) between two host across two switchtec chips. Is it possible by using current driver?

BR,
honda / Aug. 18, 2017

**Comment by lsgunth** [comment]
Hi,

Yes, the driver has experimental support for CMI in the xlink and xlink_4.12 branches. However, you need very recent firmware to use this feature and the switch must have a couple configuration parameters set. I suggest you contact your Microsemi rep who can help you get all the pieces you need.

Logan

**Comment by honda724** [comment]
Hi Logan,

I've install xlink_4.12 in my platform successfully. Could you tell me how to verify CMI function?

My platform already verified by using psxapp. I can ping from hostA to hostB successfully as below diagram.
hostA <--> switchtecA <--> switchtecB <--> hostB

Thanks,
honda / Aug. 21, 2017

**Comment by lsgunth** [comment]
Hey,

You will see the dmesg "Using crosslink configuration" if you are actually in a CMI configuration.

Logan

**Comment by honda724** [comment]
Thanks a lot. It works now.
