### ISSUE TITLE
Failure to write to large memory allocated dram

### ISSUE THREAD

**Issue by omermargolin** [Microsemi/switchtec-kernel#26]
Hi,

Trying to write to an allocated 32 MB using NTB_tool on kernel 4.10 to MW1 fails.

**on a first node, 32MB were allocated**:
[root@xbrick3014-n1 ~]# echo 33554432 > /sys/kernel/debug/ntb_tool/0000\:3b\:00.1/peer_trans1            

**Writing to the matching MW on the second node**:
[root@xbrick3014-n2 ~]# echo "peer says hello 1" > /sys/kernel/debug/ntb_tool/0000\:3b\:00.1/mw1  

**The first node does not receive the information**:
[root@xbrick3014-n1 ~]# head -c 130 /sys/kernel/debug/ntb_tool/0000\:3b\:00.1/peer_mw1 | hexdump -C  
00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000080  00 00                                             |..|
00000082

**Added printk to peer_mw_read to verify reading from the correct phy address**:

[root@xbrick3014-n1 ~]# dmesg | tail
[  348.659539] switchtec switchtec1: ntb link up
[  348.659580] ntb_hw_switchtec:switchtec_ntb_message_isr:1336: switchtec switchtec1: message: 0 00000003
[  368.476511] ntb_hw_switchtec:switchtec_ntb_mw_set_trans:370: switchtec switchtec0: MW 1: 000000f882800000 0000000002000000
[  382.599166] reading peer mw: phys addr 1067341316096

In [1]: hex(1067341316096)
Out[1]: '0xf882800000'

The same test works if allocating smaller DMA memory - see output at the bottom.
Reading and writing locally (first side to read and write from/to peer_mw1) works - reading returns the written info.

**allocating mw for peer**:
[root@xbrick3014-n1 ~]# echo 33554432 > /sys/kernel/debug/ntb_tool/0000\:86\:00.1/peer_trans1              

**reading and writing on the peer side**:
[root@xbrick3014-n2 ~]# echo "omer says hello 1" > /sys/kernel/debug/ntb_tool/0000\:86\:00.1/mw1
[root@xbrick3014-n2 ~]# head -c 130 /sys/kernel/debug/ntb_tool/0000\:86\:00.1/mw1 | hexdump -C  
00000000  6f 6d 65 72 20 73 61 79  73 20 68 65 6c 6c 6f 20  |omer says hello |
00000010  31 0a 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |1...............|
00000020  00 00 00 00 f0 8d 9c fd  0b 30 00 00 86 16 00 00  |.........0......|
00000030  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000040  00 50 6d f9 dd 00 00 00  00 00 00 00 00 00 00 00  |.Pm.............|
00000050  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000060  00 60 6d f9 dd 00 00 00  00 00 00 00 00 00 00 00  |.`m.............|
00000070  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000080  00 70                                             |.p|
00000082

**reading the the local size the peer's data fails**:
[root@xbrick3014-n1 ~]# head -c 130 /sys/kernel/debug/ntb_tool/0000\:86\:00.1/peer_mw1 | hexdump -C  
00000000  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000080  00 00                                             |..|
00000082

**but writing and read locally succeeds**:
[root@xbrick3014-n1 ~]# echo "first side says hello 1" > /sys/kernel/debug/ntb_tool/0000\:86\:00.1/peer_mw1
[root@xbrick3014-n1 ~]# head -c 130 /sys/kernel/debug/ntb_tool/0000\:86\:00.1/peer_mw1 | hexdump -C        
00000000  66 69 72 73 74 20 73 69  64 65 20 73 61 79 73 20  |first side says |
00000010  68 65 6c 6c 6f 20 31 0a  00 00 00 00 00 00 00 00  |hello 1.........|
00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000080  00 00                                             |..|
00000082

Is it possible that the translation in the switch is faulty?

Test setup:

Kernel 4.10

**the following patch was applied**:
https://github.com/Microsemi/switchtec-kernel/pull/15

**The following CMA config is used**:
CONFIG_CMA=y

CONFIG_CMA_DEBUGFS=y
CONFIG_CMA_AREAS=7
CONFIG_DMA_CMA=y
CONFIG_CMA_SIZE_MBYTES=32
CONFIG_CMA_SIZE_SEL_MBYTES=y
CONFIG_CMA_ALIGNMENT=12

CONFIG_CRYPTO_CMAC=m

the switch configs were provided by boris in: 
https://github.com/Microsemi/switchtec-kernel/pull/9
https://github.com/glimchb

**working small allocate memory**:
[root@xbrick3014-n1 ~]# dmesg -C
[root@xbrick3014-n1 ~]# insmod /var/tmp/ntrdma/drivers/ntb/test/ntb_tool.ko          
[root@xbrick3014-n1 ~]# echo 16384 > /sys/kernel/debug/ntb_tool/0000\:3b\:00.1/peer_trans1
[root@xbrick3014-n1 ~]# head -c 130 /sys/kernel/debug/ntb_tool/0000\:3b\:00.1/peer_mw1 | hexdump -C 
00000000  70 65 65 72 20 73 61 79  73 20 68 65 6c 6c 6f 20  |peer says hello |
00000010  31 0a 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |1...............|
00000020  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000080  00 00                                             |..|
00000082
[root@xbrick3014-n1 ~]# dmesg 
[  114.690525] base address 29652456308736, size 2097152
[  114.690622] base address 29635274342400, size 17179869184
[  114.690662] ntb_hw_switchtec:switchtec_ntb_link_enable:541: switchtec switchtec0: enabling link
[  114.690711] base address 32950991192064, size 2097152
[  114.690740] base address 32933809225728, size 17179869184
[  114.690774] ntb_hw_switchtec:switchtec_ntb_link_enable:541: switchtec switchtec1: enabling link
[  119.305834] ntb_hw_switchtec:switchtec_ntb_message_isr:1336: switchtec switchtec0: message: 0 00000001
[  119.305954] switchtec switchtec0: ntb link up
[  119.305989] ntb_hw_switchtec:switchtec_ntb_message_isr:1336: switchtec switchtec0: message: 0 00000003
[  119.306078] ntb_hw_switchtec:switchtec_ntb_message_isr:1336: switchtec switchtec1: message: 0 00000001
[  119.306169] switchtec switchtec1: ntb link up
[  119.306197] ntb_hw_switchtec:switchtec_ntb_message_isr:1336: switchtec switchtec1: message: 0 00000003
[  122.470249] ntb_hw_switchtec:switchtec_ntb_mw_set_trans:370: switchtec switchtec0: MW 1: 000000f882380000 0000000000004000
[  143.653758] reading peer mw: phys addr 1067336597504

[root@xbrick3014-n2 ~]# insmod /var/tmp/ntrdma/drivers/ntb/test/ntb_tool.ko   
[root@xbrick3014-n2 ~]# echo "peer says hello 1" > /sys/kernel/debug/ntb_tool/0000\:3b\:00.1/mw1

**Comment by lsgunth** [comment]
Hi,

Your problem is almost certainly 'CONFIG_CMA_ALIGNMENT=12'. This configuration option says that buffers greater than 16MiB need not be aligned to their size. However, the memory windows require that the buffers be aligned. So you'll probably find every size up to 16MiB will work.

Newer versions of the Switchtec NTB driver check this and error out if the condition is not met.

If you need to use 32MiB buffers, then you'll need to increase that configuration option. Right now it's maximum value is 12, so you'll also have to change the Kconfig file to allow setting this higher. Also, note, you'll waste a fair bit of memory doing this.

Logan

**Comment by omermargolin** [comment]
Hi Logan,

Thanks for the quick replay.
I successfully modified the CONFIG_CMA_ALIGNMENT to 18 after enlarging the max value drivers/base/Kconfig.  (support for 1G mw)

I still experience the same problem - 
Data transfer works when allocating 8MB but fails when trying to transfer 32MB.

Are there additional configurations needed?

**Comment by lsgunth** [comment]
Hmm, that's surprising, that's exactly what you'd see with the CMA_ALIGNMENT issue. You may need to increase the CMA_SIZE_MBYTES significantly as well. I'm a bit surprised it was able to allocate the full CMA.

Can you also ensure you have commit c3b2ec74ba63df1d9325c451d5cd7c8d581908b9 which checks for unaligned buffers?

**Comment by lsgunth** [comment]
Yeah, ok. You shouldn't need the unaligned_offset if the CMA is configured correctly, but I don't know why you aren't getting aligned buffers from it as you have it now.

Yeah, I guess the addr==0 is an oversight, I can't see any reason why the hardware couldn't translate an address of zero. As far as I know, removing the addr==0 condition should work so I don't know what the further problem is.

Logan

**Comment by wesleywesley** [comment]
@omermargolin 
your question have got the answer. I would like to close this issue.
