### ISSUE TITLE
swtichtec driver fails to map BAR regions

### ISSUE THREAD

**Issue by oorel** [Microsemi/switchtec-kernel#4]
The probe fails, due to that pcim_iomap_regions return -22

Maybe device isn't configured correctly, here is lspci output:

sudo lspci -s b:0.1 -vvv
0b:00.1 Memory controller: PMC-Sierra Inc. Device 8543
        Subsystem: PMC-Sierra Inc. Device 8543
        Control: I/O- Mem- BusMaster- SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx-
        Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
        Region 1: [virtual] Memory at fb400000 (32-bit, non-prefetchable) [size=4M]
        Capabilities: [40] MSI: Enable- Count=1/4 Maskable- 64bit+
                Address: 0000000000000000  Data: 0000
        Capabilities: [50] MSI-X: Enable- Count=4 Masked-
                Vector table: BAR=1 offset=00076000
                PBA: BAR=1 offset=00077000
        Capabilities: [5c] Power Management version 3
                Flags: PMEClk- DSI- D1- D2- AuxCurrent=0mA PME(D0+,D1-,D2-,D3hot+,D3cold+)
                Status: D0 NoSoftRst+ PME-Enable- DSel=0 DScale=0 PME-
        Capabilities: [64] Express (v2) Endpoint, MSI 00
                DevCap: MaxPayload 512 bytes, PhantFunc 0, Latency L0s <64ns, L1 <1us
                        ExtTag+ AttnBtn- AttnInd- PwrInd- RBE+ FLReset+
                DevCtl: Report errors: Correctable- Non-Fatal- Fatal- Unsupported-
                        RlxdOrd- ExtTag- PhantFunc- AuxPwr- NoSnoop- FLReset-
                        MaxPayload 128 bytes, MaxReadReq 512 bytes
                DevSta: CorrErr+ UncorrErr- FatalErr- UnsuppReq- AuxPwr- TransPend-
                LnkCap: Port #0, Speed 8GT/s, Width x16, ASPM L1, Exit Latency L0s unlimited, L1 <64us
                        ClockPM- Surprise- LLActRep- BwNot-
                LnkCtl: ASPM Disabled; RCB 64 bytes Disabled- CommClk-
                        ExtSynch- ClockPM- AutWidDis- BWInt- AutBWInt-
                LnkSta: Speed 8GT/s, Width x8, TrErr- Train- SlotClk+ DLActive- BWMgmt- ABWMgmt-
                DevCap2: Completion Timeout: Not Supported, TimeoutDis-, LTR+, OBFF Via message
                DevCtl2: Completion Timeout: 50us to 50ms, TimeoutDis-, LTR-, OBFF Disabled
                LnkSta2: Current De-emphasis Level: -6dB, EqualizationComplete-, EqualizationPhase1-
                         EqualizationPhase2-, EqualizationPhase3-, LinkEqualizationRequest-
        Capabilities: [100 v1] Advanced Error Reporting
                UESta:  DLP- SDES- TLP- FCP- CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP- ECRC- UnsupReq- ACSViol-
                UEMsk:  DLP- SDES- TLP- FCP- CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP- ECRC- UnsupReq- ACSViol-
                UESvrt: DLP+ SDES+ TLP- FCP+ CmpltTO- CmpltAbrt- UnxCmplt- RxOF+ MalfTLP+ ECRC- UnsupReq- ACSViol-
                CESta:  RxErr+ BadTLP+ BadDLLP+ Rollover- Timeout+ NonFatalErr+
                CEMsk:  RxErr- BadTLP- BadDLLP- Rollover- Timeout- NonFatalErr+
                AERCap: First Error Pointer: 00, GenCap+ CGenEn- ChkCap+ ChkEn-
        Capabilities: [138 v1] Device Serial Number 50-0e-00-4a-00-00-00-01
        Capabilities: [144 v1] Access Control Services
                ACSCap: SrcValid- TransBlk- ReqRedir+ CmpltRedir+ UpstreamFwd- EgressCtrl- DirectTrans+
                ACSCtl: SrcValid- TransBlk- ReqRedir- CmpltRedir- UpstreamFwd- EgressCtrl- DirectTrans-

**Comment by lsgunth** [comment]
> Region 1: [virtual] Memory at fb400000 (32-bit, non-prefetchable) [size=4M]

Yes, it looks like your configuration is strange. The switchtec driver expects to use region 0 (BAR0) for the management endpoint and yours is configured to be region 1. There's really no good reason to use region 1 over 0. I suggest you change your configuration (in Management Endpoint Settings / BAR Index) to be BAR0.

Logan

**Comment by oorel** [comment]
Thanks, but I tried this already, and hit other issue issue.

What I found is:

[   17.223789] switchtec 0000:0b:00.1: Trying BAR0
[   17.223812] pmd_set_huge: Cannot satisfy [mem 0xd2400000-0xd2600000] with a huge-page mapping due to MTRR override.
[   17.223826] switchtec 0000:0b:00.1: Trying BAR1
[   17.223829] switchtec 0000:0b:00.1: pci_resource_len for 1 returns 0
[   17.223847] switchtec switchtec0: failed to pcim_iomap_regions - retval -22
[   17.223851] switchtec switchtec0: failed to init.

**Comment by oorel** [comment]
oorel@oorel-All-Series:~/linux-4.13.5$ cat /proc/mtrr
reg00: base=0x0c0000000 ( 3072MB), size= 1024MB, count=1: uncachable
reg01: base=0x380000000000 (58720256MB), size=262144MB, count=1: uncachable
reg02: base=0x0bf000000 ( 3056MB), size=   16MB, count=1: uncachable
reg03: base=0x0c0000000 ( 3072MB), size=  256MB, count=1: write-through
reg04: base=0x0d0000000 ( 3328MB), size=   32MB, count=1: write-through
reg05: base=0x0d2000000 ( 3360MB), size=    8MB, count=1: write-through

**Comment by lsgunth** [comment]
What?? I said to change your configuration of your switch and not the code...  I don't know what you changed in the code and I'm not sure how /proc/mtrr is related at all...

I don't recommend changing the code, but if you did change it you'd have to change the second argument in pcim_iomap_regions from a 1 to a 2. I certainly don't intend on changing this in our repo.

**Comment by oorel** [comment]
Thanks a lot for helps, I am trying what you are suggesting. I had found anywhere how device should be configured by chiplink, and not even sure why it was BAR2. However I think that would be good to have driver to probe any bar, and/or have a small description on how device should be configured, especially because default configuration has EP disabled.

**Comment by lsgunth** [comment]
Yeah, I've suggested in the past the default configuration should be changed to enable the EP. 

Unfortunately, the device is so configurable it's always possible for someone to configure it in a way that doesn't work. There's really no good reason to just say the management interface should always be on the first bar. That is the default.

When I have time I might add a blurb to the readme on how to enable the EP in the switchtec configuration.

Logan

**Comment by oorel** [comment]
Should it be configured as prefetchable or not?

**Comment by lsgunth** [comment]
It's best to enable the prefetchable option.
