### ISSUE TITLE
Is there a way to use the driver to enable/disable link for a specific port?

### ISSUE THREAD

**Issue by danglus** [Microsemi/switchtec-kernel#46]
Hi,
  I'm looking for a way to enable/disable a PCIe link of a specific port from the host.
Basically, I'm trying to do automatic hot-insertion of PCI devices under certain conditions. Therefore, I want to bind the port but keep the 'enabled' box unchecked in the configuration file 'PCI port setting' of the relevant ports.

Unfortunately, the 'switchtec' app can only bind ports but not control the PCI link status of bounded ports.

   Is there a way to do it from the driver?

   Thanks,
Dan

**Comment by danglus** [comment]
@wesleywesley any insights about this one?

**Comment by kelvin-cao** [comment]
Hi, @danglus 

Wesley is on vacation. Please expect delayed response sometime next week.

Thanks,
Kelvin

**Comment by hachevin** [comment]
Hey @danglus,

This is more of a switch feature question than a driver question. It might be best to get in touch with your designated Microsemi support contacts.

Cheers,
Vince

**Comment by danglus** [comment]
Hi, I

**Comment by danglus** [comment]
The workaround is to unbind the port - a function that is already supported by the switchtec driver and user space app.
