### ISSUE TITLE
Switchtec Kernel fails to compile on Cavium ARM system running Kernel 4.11

### ISSUE THREAD

**Issue by yungwesl** [Microsemi/switchtec-kernel#6]
I'm trying to build the kernel driver but I am getting errors related to implicit declarations of the following two functions:

cdev_device_add
cdev_device_del

The error in the compiler on ARM is:
error: implicit declaration of function 'cdev_device_add' [-Werror=implicit-function-declaration]
rc=cdev_device_add(&stdev->cdev, &stdev->dev);

Do I need to change switchtec.c and pre-declare these two functions somehow?

**Comment by lsgunth** [comment]
Hey,

No, this is likely an indication of using the wrong backport branch with the kernel version you are using. 

Please ensure you use the proper branch: "backport_4.8_to_4.11"

Logan

**Comment by yungwesl** [comment]
Sweet let me check thanks Logan.
