### ISSUE TITLE
MSIX support in Switchtec driver

### ISSUE THREAD

**Issue by alfonder** [Microsemi/switchtec-kernel#99]
AMD and Intel NTB hw drivers use MSIX and allocate multiple interrupt vectors. Meanwhile Switchtec driver allocates PCI IRQ vector and thus DB vector count is always 1. 
Is there a way to modify Switchtec driver that it could use multiple MSIX vectors?

**Comment by lsgunth** [comment]
Not sure where you get that idea. The switchtec driver does use MSIX vectors.

See https://github.com/Microsemi/switchtec-kernel/blob/f86407a0160e8d5ec3d288707c4a88be077991a2/switchtec.c#L1491
